- name: Ensure libselinux-python is installed
  become: true
  package:
    name: libselinux-python
    state: present

- name: Ensure iptables ports are open
  become: true
  iptables:
    chain: INPUT
    source: "{{ nagios_server }}"
    jump: ACCEPT
    protocol: "tcp"
    destination_port: "5666"
    comment: "Allow Nagios Server access to NRPE"

